/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De03;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyễn Xuân Anh Thư
 */
public class QLNV extends javax.swing.JFrame {
    ArrayList<NhanVien> listnv = new ArrayList<>();

    /**
     * Creates new form QLNV
     */
    public QLNV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_hoten = new javax.swing.JLabel();
        tf_hoten = new javax.swing.JTextField();
        jb_ngaysinh = new javax.swing.JLabel();
        tf_ngaysinh = new javax.swing.JTextField();
        jb_gioitinh1 = new javax.swing.JLabel();
        tf_phongban = new javax.swing.JTextField();
        jb_gioitinh3 = new javax.swing.JLabel();
        tf_thamnien = new javax.swing.JTextField();
        jb_diachi = new javax.swing.JLabel();
        tf_diachi = new javax.swing.JTextField();
        jb_gioitinh = new javax.swing.JLabel();
        tf_gioitinh = new javax.swing.JTextField();
        jb_gioitinh2 = new javax.swing.JLabel();
        tf_hsl = new javax.swing.JTextField();
        jb_gioitinh4 = new javax.swing.JLabel();
        tf_luongcoban = new javax.swing.JTextField();
        bt_docfile = new javax.swing.JButton();
        bt_hienthids = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_hoten.setText("Họ tên");

        tf_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hotenActionPerformed(evt);
            }
        });

        jb_ngaysinh.setText("Ngày sinh");

        tf_ngaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ngaysinhActionPerformed(evt);
            }
        });

        jb_gioitinh1.setText("Phòng ban");

        tf_phongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phongbanActionPerformed(evt);
            }
        });

        jb_gioitinh3.setText("Thâm niên");

        tf_thamnien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_thamnienActionPerformed(evt);
            }
        });

        jb_diachi.setText("Địa chỉ");

        tf_diachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_diachiActionPerformed(evt);
            }
        });

        jb_gioitinh.setText("Giới tính");

        tf_gioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_gioitinhActionPerformed(evt);
            }
        });

        jb_gioitinh2.setText("Hệ số lương");

        tf_hsl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hslActionPerformed(evt);
            }
        });

        jb_gioitinh4.setText("Lương cơ bản");

        tf_luongcoban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_luongcobanActionPerformed(evt);
            }
        });

        bt_docfile.setText("Đọc file");
        bt_docfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_docfileActionPerformed(evt);
            }
        });

        bt_hienthids.setText("Hiển thị DS");
        bt_hienthids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hienthidsActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Phòng Ban", "Hệ số lương", "Thâm niên", "Lương cơ bản", "Họ Tên", "Ngày Sinh", "Giới tính", "Địa chỉ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_gioitinh1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_phongban, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_ngaysinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_hoten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_gioitinh3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(298, 298, 298)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_diachi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_gioitinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_gioitinh2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_hsl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_gioitinh4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_docfile)
                .addGap(42, 42, 42)
                .addComponent(bt_hienthids)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_hoten)
                    .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_diachi)
                    .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_ngaysinh)
                    .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_gioitinh)
                    .addComponent(tf_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_gioitinh1)
                    .addComponent(tf_phongban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_gioitinh2)
                    .addComponent(tf_hsl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_gioitinh3)
                    .addComponent(tf_thamnien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_gioitinh4)
                    .addComponent(tf_luongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_hienthids)
                    .addComponent(bt_docfile))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hotenActionPerformed

    private void tf_ngaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ngaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ngaysinhActionPerformed

    private void tf_phongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phongbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phongbanActionPerformed

    private void tf_thamnienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_thamnienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_thamnienActionPerformed

    private void tf_diachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_diachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_diachiActionPerformed

    private void tf_gioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_gioitinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_gioitinhActionPerformed

    private void tf_hslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hslActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hslActionPerformed

    private void tf_luongcobanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_luongcobanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_luongcobanActionPerformed

    private void bt_docfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_docfileActionPerformed
        try {
             String line;
            FileReader fr = new FileReader("nv.dat");
            BufferedReader br = new BufferedReader(fr);
            while((line = br.readLine())!= null){
               String[] result = line.split("\\$");
               NhanVien nv1 = new NhanVien( result[0],Float.parseFloat(result[1]), Integer.parseInt(result[2]), Float.parseFloat(result[3]),result[4], result[5], result[6], result[7]);
               listnv.add(nv1);
            }
            br.close();
            fr.close();
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Không tìm thấy file");
        } catch (IOException ex) {
            Logger.getLogger(QLNV.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, " tìm thấy file");
    }//GEN-LAST:event_bt_docfileActionPerformed

    private void bt_hienthidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hienthidsActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for(int i = 0; i<listnv.size();i++){
            String pb = listnv.get(i).getPhongBan();
            Float hsl = listnv.get(i).getHeSoLuong();
            int tn = listnv.get(i).getThamNien();
            Float lcb = listnv.get(i).getLuongCoBan();
            String ht = listnv.get(i).getHoTen();
            String ns = listnv.get(i).getNgaySinh();
            String gt = listnv.get(i).getGioiTinh();
            String dc = listnv.get(i).getDiaChi();
            
            Object[] a = {pb,hsl,tn,lcb,ht,ns,gt,dc};
            model.addRow(a);
        }
    }//GEN-LAST:event_bt_hienthidsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_docfile;
    private javax.swing.JButton bt_hienthids;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jb_diachi;
    private javax.swing.JLabel jb_gioitinh;
    private javax.swing.JLabel jb_gioitinh1;
    private javax.swing.JLabel jb_gioitinh2;
    private javax.swing.JLabel jb_gioitinh3;
    private javax.swing.JLabel jb_gioitinh4;
    private javax.swing.JLabel jb_hoten;
    private javax.swing.JLabel jb_ngaysinh;
    private javax.swing.JTextField tf_diachi;
    private javax.swing.JTextField tf_gioitinh;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_hsl;
    private javax.swing.JTextField tf_luongcoban;
    private javax.swing.JTextField tf_ngaysinh;
    private javax.swing.JTextField tf_phongban;
    private javax.swing.JTextField tf_thamnien;
    // End of variables declaration//GEN-END:variables
}
