/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iofile;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;


/**
 *
 * @author Nguyễn Xuân Anh Thư
 */
public class QuanLiXeForm extends javax.swing.JFrame {
    private DanhSachXeNoiThanh dsxenoi = new DanhSachXeNoiThanh();
    public QuanLiXeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jb_machuyen = new javax.swing.JLabel();
        tf_machuyen = new javax.swing.JTextField();
        jb_taixe = new javax.swing.JLabel();
        tf_taixe = new javax.swing.JTextField();
        jb_soxe = new javax.swing.JLabel();
        tf_soxe = new javax.swing.JTextField();
        jb_doanhthu = new javax.swing.JLabel();
        tf_doanhthu = new javax.swing.JTextField();
        jb_sotuyen = new javax.swing.JLabel();
        tf_sotuyen = new javax.swing.JTextField();
        jb_sokm = new javax.swing.JLabel();
        tf_sokm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_view = new javax.swing.JTextArea();
        bt_thoat = new javax.swing.JButton();
        bt_themxe = new javax.swing.JButton();
        bt_luudsxe = new javax.swing.JButton();
        bt_modanhsachxe = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_machuyen.setText("Mã chuyến");

        tf_machuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_machuyenActionPerformed(evt);
            }
        });

        jb_taixe.setText("Tài xế");

        tf_taixe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_taixeActionPerformed(evt);
            }
        });

        jb_soxe.setText("Số xe");

        tf_soxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_soxeActionPerformed(evt);
            }
        });

        jb_doanhthu.setText("Doanh thu");

        tf_doanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_doanhthuActionPerformed(evt);
            }
        });

        jb_sotuyen.setText("Số tuyến");

        tf_sotuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sotuyenActionPerformed(evt);
            }
        });

        jb_sokm.setText("Số km đi được");

        tf_sokm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_sokmActionPerformed(evt);
            }
        });

        ta_view.setColumns(20);
        ta_view.setRows(5);
        jScrollPane2.setViewportView(ta_view);

        bt_thoat.setText("Thoát");
        bt_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_thoatActionPerformed(evt);
            }
        });

        bt_themxe.setText("Thêm xe");
        bt_themxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themxeActionPerformed(evt);
            }
        });

        bt_luudsxe.setText("Lưu danh sách xe");
        bt_luudsxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_luudsxeActionPerformed(evt);
            }
        });

        bt_modanhsachxe.setText("Mở danh sách xe");
        bt_modanhsachxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modanhsachxeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb_machuyen)
                                .addComponent(jb_soxe))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jb_sotuyen)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_soxe, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_doanhthu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_machuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jb_taixe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_taixe, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tf_sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_sokm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_sokm, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(bt_themxe)
                .addGap(18, 18, 18)
                .addComponent(bt_luudsxe)
                .addGap(18, 18, 18)
                .addComponent(bt_modanhsachxe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_thoat)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_machuyen)
                    .addComponent(tf_machuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_taixe)
                    .addComponent(tf_taixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_soxe)
                    .addComponent(tf_soxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_doanhthu)
                    .addComponent(tf_doanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_sotuyen)
                    .addComponent(tf_sotuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_sokm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_sokm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_thoat)
                    .addComponent(bt_themxe)
                    .addComponent(bt_luudsxe)
                    .addComponent(bt_modanhsachxe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_machuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_machuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_machuyenActionPerformed

    private void tf_taixeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_taixeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_taixeActionPerformed

    private void tf_soxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_soxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_soxeActionPerformed

    private void tf_doanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_doanhthuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_doanhthuActionPerformed

    private void tf_sotuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sotuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sotuyenActionPerformed

    private void tf_sokmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_sokmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_sokmActionPerformed

    private void bt_themxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themxeActionPerformed
        String mc = this.tf_machuyen.getText();
        String tx = this.tf_taixe.getText();
        String sx = this.tf_soxe.getText();
        float dt = Float.parseFloat(this.tf_doanhthu.getText());
        String st = this.tf_sotuyen.getText();
        float sokm = Float.parseFloat(this.tf_sokm.getText());
        ChuyenXeNoiThanh xenoi = new ChuyenXeNoiThanh(st,sokm,mc,tx,sx,dt);
        if(dsxenoi.themMotXeNoiThanh(xenoi) == true){
            JOptionPane.showMessageDialog(null,"Đã thêm xe mới thành công!","Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null,"Thêm xe mới thất bại do trùng mã chuyến!","Thông báo",JOptionPane.ERROR_MESSAGE);
                    
        }
        
    }//GEN-LAST:event_bt_themxeActionPerformed

    private void bt_luudsxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_luudsxeActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView());
        int returnvalue = jfc.showSaveDialog(null); // Mở file để Save
        if(returnvalue == JFileChooser.APPROVE_OPTION){
            File selectedfile = jfc.getSelectedFile();
            try {
                FileOutputStream fos = new FileOutputStream(selectedfile.getAbsolutePath());
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(this.dsxenoi);
                oos.close();
            } catch (IOException ioex) {
                JOptionPane.showMessageDialog(null,"Lưu không thành công!","Thông báo",JOptionPane.ERROR_MESSAGE);
                return;
            } 
            JOptionPane.showMessageDialog(null,"Lưu file thành công!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_luudsxeActionPerformed

    private void bt_modanhsachxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modanhsachxeActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView());
        int returnvalue = jfc.showOpenDialog(null); // Mở file để Open.
        if(returnvalue == JFileChooser.APPROVE_OPTION){
            File selectedfile = jfc.getSelectedFile();
            try{
                FileInputStream fis = new FileInputStream(selectedfile.getAbsolutePath());
                ObjectInputStream ois = new ObjectInputStream(fis);
                dsxenoi = (DanhSachXeNoiThanh)ois.readObject();
                ois.close();
            }
            catch(Exception ex) {
               JOptionPane.showMessageDialog(null,"Error!");
                return;
            } 
           ta_view.setText(this.dsxenoi.toString());
        }
    }//GEN-LAST:event_bt_modanhsachxeActionPerformed

    private void bt_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_thoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiXeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiXeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_luudsxe;
    private javax.swing.JButton bt_modanhsachxe;
    private javax.swing.JButton bt_themxe;
    private javax.swing.JButton bt_thoat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jb_doanhthu;
    private javax.swing.JLabel jb_machuyen;
    private javax.swing.JLabel jb_sokm;
    private javax.swing.JLabel jb_sotuyen;
    private javax.swing.JLabel jb_soxe;
    private javax.swing.JLabel jb_taixe;
    private javax.swing.JTextArea ta_view;
    private javax.swing.JTextField tf_doanhthu;
    private javax.swing.JTextField tf_machuyen;
    private javax.swing.JTextField tf_sokm;
    private javax.swing.JTextField tf_sotuyen;
    private javax.swing.JTextField tf_soxe;
    private javax.swing.JTextField tf_taixe;
    // End of variables declaration//GEN-END:variables
}
